# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ed2a5bd7d35c810c5c69f8eefc6eb3f02e8fb2b5d0543d660cb645ad5446fb0b148c57dfa8ccbef1896f16aa84a54fff84ec85251078b7109dc5301e909adc7

test:
  secret_key_base: ad904be60b828d136c75ada0bdc55995dfa75c6d43a95c062fd38433ff77d982c89e1b8a4f77a9f77654c46bba6de69f4b8c1b74233af0d00c2af59e3f05eeca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
